{ ******************************************************* }
{ }
{ Pascal Script Source File }
{ Run by RemObjects Pascal Script in CnWizards }
{ }
{ Generated by CnPack IDE Wizards }
{ }
{ ******************************************************* }

program CommentCode;

uses
  Windows, SysUtils, Classes, CnWizIdeUtils;

var
  Lines: TStringList;
  i:     Integer;

begin
  Lines := TStringList.Create;
  try
	if IdeGetEditorSelectedLines(Lines) then begin
	  for i := 0 to Lines.Count - 1 do begin
		Lines[i] := StringReplace(Lines[i], '	', '    ', [rfReplaceAll]);
		if ( Pos(  '///', Lines[i]) = 0 ) then begin
		  Lines[i] := '///' + Lines[i]; //um tab por 4 espaços
		end;
	  end;
	  IdeSetEditorSelectedLines(Lines);
	end;
  finally
	Lines.Free;
  end;

end.
